### ISSUE TITLE
crear CRUD eventos

### ISSUE THREAD

**Issue by juandi1** [helpetproject/webapp#17]
- Lugar | String | 255 | obligatorio
- Ciudad | uuid |   | obligatorio
- Dirección | String | 255 | 
- Titulo del evento | string | 100 | obligatorio
- Descripción del evento. | text |   |  
- Fecha | date |   | obligatorio
- Hora inicio. | time |   |  
- Hora fin. | time |   |

**Comment by elduglas** [comment]
:100:
