### ISSUE TITLE
Crear CRUD fundaciones con los siguientes campos

### ISSUE THREAD

**Issue by juandi1** [helpetproject/webapp#25]
- Nombre
- Ciudad.
- Dirección
- Logo
- Página web
- Número de contacto
- Número de contacto adicional
- Correo electrónico.

**Comment by pollcaz** [comment]
@juandi1 @elduglas  Por favor me confirman en el issue cuales deben ser campos obligatorios y si deben tener algùn formato en especial y/o validaciòn al ser ingresado, gracias!

**Comment by elduglas** [comment]
- Nombre | string | 100 | obligatorio
- Ciudad. | uuid |   | obligatorio
- Dirección | string | 100 | obligatorio
- Logo | string | 255 |  
- Página web | string | 60 |  
- Número de contacto | string | 20 | obligatorio
- Número de contacto adicional | string | 20 |  
- Correo electrónico. | string | 50 | obligatorio
- Estado. | boleano |   | obligatorio
- Fecha de registro en helpet | date |   | obligatorio

**Comment by pollcaz** [comment]
@elduglas @juandi1 creo que el ùltimo campo sobra( fecha de registro), ya que lo podemos manejar con el created_at por defecto al momento de crear el registro

**Comment by pollcaz** [comment]
@elduglas vamos a manejar sòlo dos contactos o vamos a dar la opciòn de que pueda crearle los contactos que desee osea màs de 2?

**Comment by elduglas** [comment]
> @elduglas vamos a manejar sòlo dos contactos o vamos a dar la opciòn de que pueda crearle los contactos que desee osea màs de 2?

Para el MVP1 solo esos 2
